spring:
  application:
    name: push
  kafka:
    bootstrap-servers: remote.host.com:9093
    producer:
      acks: -1
      retries: 3
      compression-type: gzip
      properties:
        linger.ms: 0



websocket:
  cluster:
    topic: push

server:
  port: 8082
