spring:
  data:
    redis:
      host: remote.host.com
      port: 6379
      password: nw123456
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8
  application:
    name: broker
  kafka:
    bootstrap-servers: remote.host.com:9093
    consumer:
      group-id: test-consumer-group #标识此消费者所属的消费者组的唯一字符串，这里只要你是默认安装，那就是这个，不用修改
      enable-auto-commit: false #消费者的偏移量是否在后台自动提交，默认为 true
      auto-commit-interval: 5000 #如果enable.auto.commit=true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为 5000
      # 当 Kafka 中没有初始偏移量或者服务器上不再存在当前偏移量时该怎么办，可选的值有 latest、earliest、exception、none，默认值为 latest
      # latest：重置为分区中最新的 offset(消费分区中新产生的数据)、earliest:重置为分区中最小的 offset
      auto-offset-reset: earliest
      properties:
        session.timeout.ms: 180000 #消费会话超时时间(超过这个时间consumer没有发送心跳,就会触发 rebalance(重新平衡) 操作)
        request.timeout.ms: 120000 #消费请求超时时间
      max-poll-records: 5
    listener:
      type: single
      ack-mode: manual
websocket:
  cluster:
    connectServiceName: connect
    topic: push

server:
  port: 8087
